daemp:
  fields:
    rum:
      example: "01M2K0DJ1MDN20MH0VWVE1N67A"
      selector:
        text:
    omraade:
      selector:
        area:
    lamper:
      selector:
        entity:
          domain: light
          multiple: true
    lysstyrke:
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

anvend_lys:
  fields:
    rum:
      selector:
        text:
    omraade:
      selector:
        area:
    lamper:
      selector:
        entity:
          domain: light
          multiple: true
    lys:
      required: true
      example: '{"type": "hvid", "lysstyrke": 80, "kelvin": 2700}'
      selector:
        object:

anvend_scene:
  fields:
    rum:
      selector:
        text:
    omraade:
      selector:
        area:
    lamper:
      selector:
        entity:
          domain: light
          multiple: true
    scene:
      required: true
      selector:
        text:
    lysstyrke:
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

hold:
  fields:
    rum:
      selector:
        text:
    omraade:
      selector:
        area:
    lamper:
      selector:
        entity:
          domain: light
          multiple: true
    til:
      required: true
      selector:
        boolean:
